# Generated by Django 4.0.4 on 2022-05-27 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=200)),
                ('sana', models.DateField(auto_now_add=True)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.muallif')),
            ],
        ),
    ]
